### PR TITLE
Upgrade to lego v4.6.0

### PR DESCRIPTION
**Pull request by matan129**
I know this module is deprecated, but I really need support for [Porkbun](https://porkbun.com/) which was added quite recently to Lego.

### CODE REVIEW

**Comment by mholt** [comment]
Hmm, that doesn't quite look right. The resulting go.mod should be:


```
module github.com/caddy-dns/lego-deprecated

go 1.14

require (
	github.com/caddyserver/caddy/v2 v2.5.1
	github.com/go-acme/lego/v4 v4.6.0
	github.com/mholt/acmez v1.0.2
)
```

Please verify that your `go get` commands were run properly :thinking:  (and run `go mod tidy`)

**Comment by matan129** [comment]
Hiya, that indirect requirement was added by `go get -u github.com/go-acme/lego/v4`, and `go mod tidy` indeed fixed it.

Thanks!

P.S. Pushed as a separate commit, you're welcome to squash them if you'd like...

**Review by mholt — APPROVED** [review]
Perfect! Thanks.

**Comment by matan129** [comment]
@mholt , is there anything else to be done so this module will become available? Downloading a fresh binary from the official site comes with `dns.providers.lego_deprecated v0.0.0-20220214194914-71728235b643` (which is dated to the commit before this PR got merged)

**Comment by mholt** [comment]
It's probably from the build cache. Type the version (commit or branch or tag) into the version field and try again.

**Pull request merged**
