### PR TITLE
Upgrade to lego v4.9.1 (#8)

### PR DESCRIPTION
**Pull request by claycooper**

### CODE REVIEW

**Comment by marcbinz** [comment]
Hey @claycooper 👋 

I do not want to bother you, but is there any holdup in regards to merging this PR?
lego 4.9 introduces a fix that our company setup for caddy needs to resolve certificates via All-Inkl.
(There would also be another version bump 4.9.1 which could be included as well)

I am not yet a contributor here, but if there is anything I can do to help, please let me know 🙏  Thanks!

**Comment by mholt** [comment]
Thanks for the PR. (Sorry I missed this earlier)

Could you run `go mod tidy` and, I guess while we're at it, upgrade to 4.9.1 as @marcbinz mentioned? Otherwise I'll be happy to do it separately. But since you've already opened the PR :)

**Comment by claycooper** [comment]
@mholt I think I did what you asked. I'm not well-versed in Go or Git so it's a learning journey.

**Comment by mholt** [comment]
@claycooper Awesome, thanks. Just to check, did you run `go mod tidy` at the end just before committing? Maybe that's just what it does now, but I'd expect the file to be a little smaller.

**Comment by claycooper** [comment]
Yes, I updated the version and ran go mod today.

**Review by mholt — APPROVED** [review]
Alrighty then. Thank you!

**Comment by marcbinz** [comment]
Hey guys, thank you for the quick resolution! 😀

**Pull request merged**
